import Navbar from "@/components/navbar/Navbar";
import "./globals.css";
import { Sora } from "next/font/google";
import Footer from "@/components/footer/Footer";
import Bottom from "@/components/bottom/Bottom";
import { Toaster } from "react-hot-toast";
export const sora = Sora({ subsets: ["latin"] });

const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={sora.className}>
        <Navbar />
        {children}
        <Bottom />
        <Footer />
        <Toaster />
      </body>
    </html>
  );
}
